# Generated by Django 5.1.4 on 2024-12-31 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aghendi', '0008_alter_agenda_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='key_visible',
            field=models.BooleanField(default=False),
        ),
    ]
